import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const defaults = {
  plugin: resolve(root, 'release/feishu-long-connection/dist/index.mjs'),
  out: resolve(root, 'release/profiles/desktop.patch.yml'),
}
const { values } = parseArgs({
  options: {
    plugin: { type: 'string' },
    out: { type: 'string' },
    workspace: { type: 'string' },
    botName: { type: 'string', default: 'ToneClaw' },
    'billing-plugin': { type: 'string' },
  },
})

const pluginPath = resolve(values.plugin ?? defaults.plugin)
const outputPath = resolve(values.out ?? defaults.out)
if (!isAbsolute(pluginPath)) throw new Error('--plugin must be absolute after resolution')
const workspacePath = values.workspace === undefined
  ? `!!js "(process.getBuiltinModule('node:fs').mkdirSync(dshHomePath('workspaces/toneclaw'), { recursive: true }), dshHomePath('workspaces/toneclaw'))"`
  : `'${resolve(values.workspace).replaceAll('\\', '/')}'`

const pluginReference = relative(dirname(outputPath), pluginPath).replaceAll('\\', '/')
const billingArgument = values['billing-plugin']
const billingReference = billingArgument === undefined
  ? undefined
  : relative(dirname(outputPath), resolve(billingArgument)).replaceAll('\\', '/')
const billingBlock = billingReference === undefined ? '' : `
    - id: billing-host
      name: '${billingReference}'
      config:
        dbPath: !!js "(process.getBuiltinModule('node:fs').mkdirSync(dshHomePath('data/toneclaw'), { recursive: true }), dshHomePath('data/toneclaw/billing.sqlite'))"
        dataDir: !!js "(process.getBuiltinModule('node:fs').mkdirSync(dshHomePath('data/toneclaw'), { recursive: true }), dshHomePath('data/toneclaw'))"
        workspaceId: workspace-local
`
const patch = `# Generated by toneclaw-product; do not put developer checkout paths here.
- insert:
    - id: webhook-runtime
      name: '@deepseek-ai/dsh-webhook'

${billingBlock}    - id: feishu-long-connection
      name: '${pluginReference}'
      config:
        source: primary-feishu
        appIdEnv: DSH_FEISHU_APP_ID
        appSecretEnv: DSH_FEISHU_APP_SECRET
        loggerLevel: info
        consoleArrival: true

    - id: feishu-channel
      name: '@deepseek-ai/dsh-webhook-feishu'
      config:
        source: primary-feishu
        appIdEnv: DSH_FEISHU_APP_ID
        appSecretEnv: DSH_FEISHU_APP_SECRET
        workspacePath: ${workspacePath}
        agentPreset: standard
        permissionPreset: read-only
        botName: '${values.botName}'
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, patch, 'utf8')
console.log(`profile: ${outputPath}`)
console.log(`plugin:  ${pluginReference}`)
